##################################################################################################
#   Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details  ################   ESTO SE CONECTA CON...
---
##################################################################################################
#   Details deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details         ############# ... ESTO 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details     ############# ... Y CON ESTO
    spec:
      containers:
      - name: details
        image: grupo40/details:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---
