##################################################################################################
# Productpage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
##################################################################################################
# Productpage deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: grupo40/productpage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---
##################################################################################################
# Productpage IP externa
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-external-service
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30000  #Este es el puerto que debemos poner en el navegador (rango entre 30000-32767)
    name: http
  selector:
    app: productpage
  type: LoadBalancer   #asigna al servicio una IP externa y acepta peticiones externas-> minikube service productpage-external-service
---
